<div id="footer">
    <div class="container">
        <p class="text-muted">&copy; 2013 - <?=date('Y'); ?> <a href="https://islamic.network" target="_blank">Islamic Network</a> and respective contributors. Read the <a href="/credits-and-terms">credits, terms and conditons</a> for more information.</p>
    </div>
</div>

<!-- Notices and Floaters -->
<?php if ($noticeFloater != '') { ?>
<div class="noticeFloater">
    <span class="btn btn-danger btn-red">
        <?=$noticeFloater;?>
        <span class="glyphicon glyphicon-chevron-up btn" id="hideNoticeFloater" style="width: 20px;"></span>
    </span>

</div>
<script>
    $(function() {
        $('#hideNoticeFloater').on('click', function() {
            $('.noticeFloater').slideUp();
        });
    });
</script>
<?php } ?>

<?php if ($holydayFloater) { ?>
<div class="holydayFloater">
    <a href="/islamic-holidays">
        <span class="btn btn-danger btn-red">
            Upcoming Holy Day: <b><?php echo implode(', ', $holydayFloater['hijri']['holidays']); ?></b> on <?php echo $holydayFloater['gregorian']['day']; ?> <?php echo $holydayFloater['gregorian']['month']['en']; ?> <?php echo $holydayFloater['gregorian']['year']; ?> 
        </span></a>
    <span class="glyphicon glyphicon-chevron-down btn" id="hideHolydayFloater"></span>    
</div>
<!-- Notices and Floaters End -->

<!-- Include all compiled bootstrap plugins (below), or include individual files as needed-->

<script>
$(function() {
   $('#hideHolydayFloater').on('click', function() {
      $('.holydayFloater').slideUp(); 
   });
});
</script>
<?php } ?>

<div class="nextPrayer panel">
    <span id="time" class="btn"></span>
    <span class="glyphicon glyphicon-resize-full btn" id="fullscreen" ria-hidden="true"></span>
    <span class="glyphicon glyphicon-resize-small hidden btn" id="normalscreen" ria-hidden="true"></span>
</div>

<script src="/js/app.js" type="text/javascript"></script>
</body>
</html>
