<div id="footer">
    <div class="container">
        <p class="text-muted">&copy; 2013 - <?=date('Y'); ?> Respective contributors. Read the <a href="/credits-and-terms">credits, terms and conditons</a> for more information.</p>
    </div>
</div>
<?php if ($holydayFloater) { ?>
<div class="holydayFloater">
    <a href="/islamic-holidays">
        <span class="btn btn-danger btn-red">
            Upcoming Holy Day: <b><?php echo implode(', ', $holydayFloater['hijri']['holidays']); ?></b> on <?php echo $holydayFloater['gregorian']['day']; ?> <?php echo $holydayFloater['gregorian']['month']['en']; ?> <?php echo $holydayFloater['gregorian']['year']; ?> 
        </span></a>
    <span class="caret linkify" id="hideHolydayFloater"></span>    
</div>
<!-- Include all compiled bootstrap plugins (below), or include individual files as needed-->

<script>
$(function() {
   $('#hideHolydayFloater').on('click', function() {
      $('.holydayFloater').slideUp(); 
   });
});
</script>
<?php } ?>

<div class="nextPrayer panel">
        <span id="time" class="btn"></span>
<span class="dropup">
    <span class="caret linkify" id="hideNextPrayer"></span>
</span>    
</div>

<script src="/js/app.js" type="text/javascript"></script>
</body>
</html>
