<!DOCTYPE html>
<?php
// Load all backgrounds
$bgsJson = file_get_contents('backgrounds.json', true);
$bgs = json_decode($bgsJson);
?>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="title" content="<?= $title; ?>" />
        <meta name="description" content="<?= $title; ?> - Prayer Times and Adhan Player" />
        <title><?= $title; ?> - Prayer Times and Adhan Player</title>
        <link rel="stylesheet" href="https://islamcdn.com/aladhan.com/js/bootstrap/3.3.7/css/bootstrap.min.css">
        <link href="/css/sticky-footer.css" rel="stylesheet">
        <link rel="stylesheet" href="/css/bootstrap.css">
        <link rel="stylesheet" href="/css/aladhan.css">
        <script src="https://islamcdn.com/aladhan.com/js/jquery-3.1.1.min.js"></script>
        <script src="https://islamcdn.com/aladhan.com/js/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>
        <body style="background-image: url('//islamcdn.com/aladhan.com/images/background.jpg'); background-size: cover;">
        <!-- Google Analytics -->
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
            
            ga('create', 'UA-3749682-25', 'aladhan.com');
            //ga('require', 'displayfeatures');
            ga('send', 'pageview');
        </script>
        <!-- Assign JS variables for app.js to load backgrounds -->
        <script>
            var bgsJson = <?=$bgsJson;?> 
        </script>
