<!DOCTYPE html>
<?php
// Load all backgrounds
$bgsJson = file_get_contents('backgrounds.json', true);
$bgs = json_decode($bgsJson);
$firstBg = 11;
?>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="title" content="<?= $title; ?>" />
        <meta name="description" content="<?= $title; ?> - Prayer Times and Adhan Player" />
        <title><?= $title; ?> - Prayer Times and Adhan Player</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link href="/css/sticky-footer.css" rel="stylesheet">
        <link rel="stylesheet" href="/css/bootstrap.css">
        <link rel="stylesheet" href="/css/aladhan.css">
        <script
  src="https://code.jquery.com/jquery-3.1.1.min.js"
  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
  crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </head>
        <!--<body style="background-image: url(<?=$bgs->files[$firstBg]; ?>); background-size: cover;"> -->
        <body style="background-image: url('//cdn.meezaan.net/sites/aladhan.com/images/background.jpg'); background-size: cover;">
        <!-- Google Analytics -->
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
            
            ga('create', 'UA-3749682-25', 'aladhan.com');
            //ga('require', 'displayfeatures');
            ga('send', 'pageview');
        </script>
        <!-- Assign JS variables for app.js to load backgrounds -->
        <script>
            var bgsJson = <?=$bgsJson;?> 
        </script>
