<?php include_once('common/header.phtml'); ?>
<?php include_once('common/navigation.phtml'); ?>

<div class="container panel">
    <?php include_once('common/bismillah.phtml'); ?>
    <div class="page-header">
        <h2>About the Al Adhan Service</h2>
    </div>
    <p>
        This application was built, inspired by God (like everything good I can do and have ever done), through my wife (God bless her, she is always the medium of inspiration) who missed the sound of Adhan 5 times a day living in a country with few mosques. I
        was not aware of other services at the time, so a simple webpage that we could leave running on one of the computers
        that was always on seemed like the simplest way to hear Adhan 5 times a day.
    </p>
    <p>
        This application is also useful for when you are travelling. You don't need to change the time on your computer, it
        will look up the time for the region you select from the cloud and play Adhan when the time is correct. However, you
        will need to be connected to the internet for this.
    </p>
    <p>
        At some point I may find the time to make a completely offline version available too, but then you will always rely on
        the time of your device. I think there are already some mobile apps and Chrome specific apps out there that do this.
    </p>
    <p>
        Consequent research also revealed that others were looking for an API to get Salat / Prayer timings online, so I set
        up a RESTful API to get prayer times on a given day. You can learn more about the API and how to use it on
        <a href="/prayer-times-api">https://aladhan.com/rest-api</a>.
    </p>
    <p>
        I owe a great deal of thanks to the authors and developers of Pray Times (<a href="http://praytimes.org">http://praytimes.org</a>) as
        the heart of the API and the application is built on their code.
    </p>
    <p>
        This application and website is built on virtually all open source tools and would not have been possible without
        the contribution of the millions of developers out there. For more information on the tools used to build this site,
        please see the <a href="/credits-and-terms">credits, terms and conditions</a> page. The site uses Bootsrap 3 and should
        run and stream the Adhan on all modern browsers.
    </p>
</div>

<?php include_once('common/footer.phtml'); ?>
