<?php include_once('common/header.phtml'); ?>
<?php include_once('common/navigation.phtml'); ?>

<div class="container panel">
    <?php include_once('common/bismillah.phtml'); ?>

    <div class="page-header">
        <h2>API Clients</h2>
    </div>
    
    <p>
        API Clients are being developed to help developers get started easily. There are currently 2 clients available:
    </p>
    <ol>
        <li>PHP client available @ <a href="http://islamic-network.github.io/aladhan-api-client-php/" target="_blank">http://islamic-network.github.io/aladhan-api-client-php/</a></li>
        <li>JQuery plugin available @ <a target="_blank" href="https://github.com/islamic-network/aladhan-api-jquery-plugin">https://github.com/islamic-network/aladhan-api-jquery-plugin</a>.</li>
        <li>WordPress Plugin @ <a href="https://wordpress.org/plugins-wp/prayer-times-by-aladhan/" target="_blank">https://wordpress.org/plugins-wp/prayer-times-by-aladhan/</a></li>
        <li>Drupal Module @ <a href="https://www.drupal.org/sandbox/meezaan/2810509" target="_blank">https://www.drupal.org/sandbox/meezaan/2810509</a></li>
    </ol>
    <p>If you'd like to help write a client, please <a href="/contact">get in touch</a>.
    </p>

</div>

<?php include_once('common/footer.phtml'); ?>
