<?php include_once('common/header.phtml'); ?>
<?php include_once('common/navigation.phtml'); ?>

<div class="container panel">
    <?php include_once('common/bismillah.phtml'); ?>

    <div class="page-header">
        <h2>Who's using the AlAdhan API</h2>
    </div>
   <div class="row">
        <div class="col-lg-12 col-md-12"> 
            <h3>
                Websites, Apps and Bots
            </h3>
            <p>
                This is a non-comprehensive list of apps and websites using the AlAdhan API.
                If you use the api and would like to get your app / website added, please raise a Pull Request
                on <a href="https://github.com/islamic-network/aladhan.com/blob/master/templates/consumers-api.phtml" target="_blank">GitHub</a>.
            </p>
            <ol>
                <li><a href="https://prayertimes.org/" target="_blank">PrayerTimes.org</a></li>
                <li><a href="http://mysalaam.com/" target="_blank">MySalaam.com</a> - Global Hub of Consumers</li>
                <li><a href="http://palestina.ps/" target="_blank">Palestina.ps</a></li>
                <li><a href="http://ajman.travel/" target="_blank">Ajman.travel</a> - Ajman Tourism Website</li>
                <li><a href="http://shalat.co/" target="_blank">Shalat.co</a> - A Prayer Times Calendar</li>
                <li><a href="http://deep-red.info/#/tab/pray" target="_blank">Waktu Salat App</a></li>
                <li><a href="http://hazratkhalidmasjid.org/" target="_blank">Hazrat Khalid Masjid</a></li>
                <li><a href="http://info-halal.net/" target="_blank">Info Halal</a></li>
                <li><a href="http://reveremosque.org" target="_blank">Masjid Ar Rahma</a></li>
                <li><a href="http://infotheworld.com" target="_blank">Info the World</a></li>
                <li><a href="http://www.minbaraden.com" target="_blank">Minbar Aden</a></li>
                <li><a href="http://shashe.net" target="_blank">Shashe.net</a></li>
                <li><a href="http://islamicsocietylawrence.org" target="_blank">Islamic Centre of Lawrence</a></li>
                <li><a href="http://iftar.today" target="_blank">The iftar.today app</a></li>
                <li><a href="http://akhoonmasjid.com" target="_blank">Akhoon Masjid</a></li>
                <li><a href="http://gph.gov.sa" target="_blank">General Presidency of the Haram</a></li>
                <li><a href="http://iisna.com" target="_blank">Islamic Information and Services Network of Australasia</a></li>
                <li><a href="http://nauss.edu.sa" target="_blank">Naif Arab University for Security Services</a></li>
                <li><a href="http://www.hallf4jumah.org" target="_blank">Halls for Jumah</a></li>
                <li><a href="http://www.radioquran.tn" target="_blank">Radio Quran Tunisia</a></li>
                <li><a href="http://nissae.net" target="_blank">Nissae.net</a></li>
                <li><a href="http://jussur.net" target="_blank">Jussur.net</a></li>
                <li><a href="http://usamosques.com" target="_blank">USA Mosques</a></li>
                <li><a href="https://chrome.google.com/webstore/detail/ayattoday/nmebafllopknoonpbddekobjcmhpnejf?hl=en" target="_blank">Ayat Today</a></li>
                <li><a href="http://masjidagungkepahiang.com" target="_blank">Masjid Agung Kepahiang</a></li>
                <li><a href="http://www.eastlondonmosque.org.uk" target="_blank">East London Mosque</a></li>
                <li><a href="http://www.nogumfm.net" target="_blank">Nogum GM</a></li>
                <li><a href="http://www.al3omk.net" target="_blank">Al3omk</a></li>
                <li><a href="http://andaluspress.com" target="_blank">Andalus Press</a></li>
                <li><a href="http://wahidd.com" target="_blank">Wahidd Radio</a></li>
                <li><a href="http://jagung.net" target="_blank">Jagung</a></li>
                <li><a href="http://muxlix.uz" target="_blank">Muxlis Uzbekistan</a></li>
                <li><a href="http://www.extranews.tv" target="_blank">Extra News TV</a></li>
                <li><a href="http://www.quransaya.id" target="_blank">QuranSaya.id</a></li>
                <li><a href="http://www.ontdekdubai.nl" target="_blank">Ontdek Dubai.NL</a></li>
                <li><a href="http://scheduler.3dn.ru/" target="_blank">SalatTime</a></li>
                <li><a href="https://t.me/halalinfobot/" target="_blank">Halal Info Bot</a></li>
                <li><a href="https://www.amazon.fr/Mohamed-ARRADI-ALAOUI-Mon-Adhan-Prochaine/dp/B07Z77RCRY" target="_blank">Mon Adhan: Prochaine salat [Amazon Alexa Skill French Store]</a></li>
                <li>Air Arabia</li>
                <li>Telegram Bot - IslamPrayTime (@islamLoveRuBot)</li>
                <li><a href="https://play.google.com/store/apps/details?id=com.zainraza.calendar.world_calendar" target="_blank">World Calendar</a></li>
                <li><a href="https://5etme.com" target="_blank">5etme.com</a></li>
                <li><a href="https://play.google.com/store/apps/details?id=com.yquery.myquran" target="_blank">Qurany - قرآني</a></li>
            </ol>

            <h3>
                Repositories
            </h3>
            <ol>
                <li><a href="https://github.com/Kh4lidMD/AlAdhan/" target="_blank">Al Adhan Python wrapper</a></li>
                <li><a href="https://github.com/Soldiiier/myPray" target="_blank">MyPray</a></li>
                <li><a href="https://github.com/andela-kerinoso/adhan-bot" target="_blank"> Slack Webhook for Prayer Times</a></li>
                <li><a href="https://github.com/cousine/powerline_prayers" target="_blank">Powerline Prayer Times</a></li>
                <li><a href="https://github.com/mimiubay/salah-time" target="_blank">Salah Time</a></li>
                <li><a href="https://github.com/muba1ham/Quran" target="_blank">Quran</a> - An Android App</li>
                <li><a href="https://github.com/Sohair63/namaz" target="_blank">Namaz Ruby Gem</a></li>
                <li><a href="https://github.com/search?l=JavaScript&q=aladhan.com&type=Code&utf8=%E2%9C%93" target="_blank">And many more...</a></li>
            </ol>
        </div>
    </div>
</div>

<?php include_once('common/footer.phtml'); ?>
