<?php include_once('common/header.phtml'); ?>
<?php include_once('common/navigation.phtml'); ?>

<div class="container panel">
    <?php include_once('common/bismillah.phtml'); ?>
    <div class="page-header">
        <h1>How to get in touch</h1>
    </div>
   <p>
        If you have any suggestions or would like to say something, you can get in touch on
aladhan.com@outlook.com
    </p>

    <p>
        Please do not email any MP3 or audio files to this email address. If you'd like to get an Adhan added to the site, please drop me a line and
        I will let you know how to go about it.
    </p>

    <!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/classic-081711.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
  <div id="mc_embed_signup">
  <form action="//meezaan.us12.list-manage.com/subscribe/post?u=28e0769b91beac04101b86411&amp;id=634c36d6fa" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate="">
      <div id="mc_embed_signup_scroll">
      <a name="apiSignupForm"></a>
  	<h4 style="color: black;">Subscribe to the API / Developer Mailing List</h4>
  <div class="mc-field-group">
  	<label for="mce-EMAIL">Email Address </label>
  	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
  </div>
  <div class="mc-field-group">
  	<label for="mce-FNAME">First Name </label>
  	<input type="text" value="" name="FNAME" class="" id="mce-FNAME">
  </div>
  <div class="mc-field-group">
  	<label for="mce-LNAME">Last Name </label>
  	<input type="text" value="" name="LNAME" class="" id="mce-LNAME">
  </div>
  	<div id="mce-responses" class="clear">
  		<div class="response" id="mce-error-response" style="display:none"></div>
  		<div class="response" id="mce-success-response" style="display:none"></div>
  	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
      <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_28e0769b91beac04101b86411_634c36d6fa" tabindex="-1" value=""></div>
      <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
      </div>
  </form>
  </div>
</div>

<?php include_once('common/footer.phtml'); ?>
