<?php include_once('common/header.phtml'); ?>
<?php include_once('common/navigation.phtml'); ?>

<div class="container panel">
    <?php include_once('common/bismillah.phtml'); ?>
    <div class="page-header">
        <h1>How to get in touch</h1>
    </div>
    <p>
    If you have any suggestions or would like to say something, you can:
    </p>

    <ul>
      <li>Get in touch on
      &#115;&#117;&#112;&#112;&#111;&#114;&#116;&#064;&#105;&#115;&#108;&#097;&#109;&#105;&#099;&#046;&#110;&#101;&#116;&#119;&#111;&#114;&#107;.
      </li>
      <li>
      Join and post your query on the Islamic Network Community @ <a href="https://community.islamic.network"
      target="_blank">https://community.islamic.network</a>. This is the official supported channel for support.
      </li>
      <li>
      Join the Discord server if you'd just like to chat about something related @ <a href="https://discord.gg/FwUy69M"
      target="_blank">https://discord.gg/FwUy69M</a>.
      </li>
    </ul> 

</div>

<?php include_once('common/footer.phtml'); ?>
