<?php include_once('common/header.phtml'); ?>
<?php include_once('common/navigation.phtml'); ?>

<div class="container panel">
    <?php include_once('common/bismillah.phtml'); ?>

    <div class="page-header">
        <h2>Download High Quality Adhan MP3s</h2>
    </div>
    
    <p>
        If you would like to use the adhan MP3s used with the Adhan player @ <a href="/play">https://aladhan.com/play</a>, they can be downloaded at a shared OneDrive folder.
    </p>
    <p  style="text-align: center;">
        <br />
        <a href="https://1drv.ms/f/s!AmrVmjAdc7P2oeISmXUA5GZRvyuB4A" class="btn btn-primary">
            View and Download Adhans
        </a> <br />(links to OneDrive)
    </p>

</div>

<?php include_once('common/footer.phtml'); ?>
