<?php include_once('common/header.phtml'); ?>
<?php include_once('common/navigation.phtml'); ?>

    <div class="panel" style="margin-top: 50px; opacity: 100%;">
        <?php include_once('common/bismillah.phtml'); ?>
        <div class="page-header">
            <h2>Islamic / Hijri Calendar API</h2>
        </div>
        <rapi-doc spec-url="https://api.aladhan.com/v1/documentation/openapi/islamic-calendar/yaml"
                  theme = 'dark'
                  show-header = 'false'
                  show-info = 'true'
                  allow-authentication ='false'
                  allow-server-selection = 'true'
                  allow-api-list-style-selection ='false'
        ></rapi-doc>
        <script type="module" src="/js/rapidoc-min.js"></script>
        </head>
    </div>
<?php include_once('common/footer.phtml'); ?>