<?php include_once('common/header.phtml'); ?>
<?php include_once('common/navigation.phtml'); ?>
<link rel="stylesheet" href="/css/play.css">
<link rel="stylesheet" href="/js/mediaplayer/build/mediaelementplayer.css" />

<div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-12 col-sm-12 timings" style="">
      <h4 class="pt-heading">Prayer Times <small>for</small><br /><small><?=isset($times['timings']) ?  $times['date']['gregorian']['day'] . ' ' . $times['date']['gregorian']['month']['en'] . ', ' . $times['date']['gregorian']['year'] . ' ' . $times['date']['gregorian']['designation']['abbreviated'] . '<br />' .
$times['date']['hijri']['day'] . ' ' . $times['date']['hijri']['month']['en'] . ', ' . $times['date']['hijri']['year'] . ' ' . $times['date']['hijri']['designation']['abbreviated'] . '<br /> in ' . $city . ', ' . $country : '';?></small></h4>
        <img class="minimise-icon" width="21" style="display: none;" src="https://cdn.aladhan.com/images/minimize-icon.png" style="">
        <img class="settings-icon" width="25" style="display: none;" src="https://cdn.aladhan.com/images/settings-icon.png" style="">
        <dl class="inline-flex">
          <dt>Fajr (فجر)</dt>
          <dd class="timeFajr"><?=isset($times['timings']) ? $times['timings']['Fajr'] : '';?></dd>
          <dt>Sunrise (شروق)</dt>
          <dd class="timeSunrise"><?=isset($times['timings']) ? $times['timings']['Sunrise'] : '';?></dd>
          <dt>Zhuhr (ظهر)</dt>
          <dd class="timeDhuhr"><?=isset($times['timings']) ? $times['timings']['Dhuhr'] : '';?></dd>
          <dt>Asr (عصر)</dt>
          <dd class="timeAsr"><?=isset($times['timings']) ? $times['timings']['Asr'] : '';?></dd>
          <dt>Maghrib (مغرب)</dt>
          <dd class="timeMaghrib"><?=isset($times['timings']) ? $times['timings']['Maghrib'] : '';?></dd>
          <dt>Isha (عشاء)</dt>
          <dd class="timeIsha"><?=isset($times['timings']) ? $times['timings']['Isha'] : '';?></dd>
          <dt>Midnight</dt>
          <dd class="timeMidnight"><?=isset($times['timings']) ? $times['timings']['Midnight'] : '';?></dd>
        </dl>
        <form role="form">
            <div class="form-group">
                <label for="adhanfile">Select Adhan to play when it's time</label>
                <select id="adhanfile" name="adhanfile" class="form-control">
                    <option value="https://cdn.aladhan.com/audio/adhans/a1.mp3" selected="">Adhan by Ahmad al Nafees</option>
                    <option value="https://cdn.aladhan.com/audio/adhans/a2.mp3">Adhan by Hafiz Mustafa Özcan from Turkey</option>
                    <option value="https://cdn.aladhan.com/audio/adhans/a3.mp3">Adhan from Karl Jenkins' Mass for Peace"</option>
                    <option value="https://cdn.aladhan.com/audio/adhans/a4.mp3">Adhan from Dubai's One TV by Mishary Rashid Alafasy</option>
                    <option value="https://cdn.aladhan.com/audio/adhans/a7.mp3">Another Adhan by Mishary Rashid Alafasy</option>
                    <option value="https://cdn.aladhan.com/audio/adhans/a9.mp3">Another Adhan by Mishary Rashid Alafasy</option>
                </select>
                <label for="different_fajr_adhan">Play different Adhan at Fajr?</label>
                <input type="checkbox" id="different_fajr_adhan" name="different_fajr_adhan">
                <select id="fajrAdhanfile" name="fajrAdhanfile" class="form-control" style="display: none;">
                    <option value="https://cdn.aladhan.com/audio/adhans/fajr/f1.mp3" selected="">Fajr Adhan</option>
                </select>
            </div>
        </form>
        <hr />
        <div id="holidays" class="hidden"></div>
        <audio id="adhanplayer" src="https://cdn.aladhan.com/audio/adhans/a1.mp3" type="audio/mp3" controls="controls"></audio>
      </div>
      <div class="col-lg-9 col-md-12 col-sm-12 timings-settings" style="background-color: black; opacity: 0.8; margin: 10 0 0 0;">
        <div class="loader">
            <img src="/images/loader.svg" />
            <div>Loading</div>
        </div>
        <img class="settings-close-icon" width="25" src="https://cdn.aladhan.com/images/close-icon.png">
<?php include_once('common/bismillah.phtml'); ?>
        <div class="page-header">
            <h4>Adhan Player <small>Just select a method and enter a location</small></h2>
        </div>

        <form role="form">
          <div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label for="method">Method (<a href="/calculation-methods" target="_blank">Learn more about calculation methods</a>)</label>
            <select id="method" name="method" class="form-control">
                <option value="0">Shia Ithna-Ashari</option>
                <option value="1">University of Islamic Sciences, Karachi</option>
                <option value="2" selected>Islamic Society of North America (ISNA)</option>
                <option value="3">Muslim World League (MWL)</option>
                <option value="4">Umm al-Qura, Makkah</option>
                <option value="5">Egyptian General Authority of Survey</option>
                <option value="7">Institute of Geophysics, University of Tehran</option>
                <option value="8">Gulf Region</option>
                <option value="9">Kuwait</option>
                <option value="10">Qatar</option>
                <option value="11">Majlis Ugama Islam Singapura, Singapore</option>
                <option value="12">Union Organization Islamic de France</option>
                <option value="13">Diyanet İşleri Başkanlığı, Turkey</option>
                <option value="14">Spiritual Administration of Muslims of Russia</option>
            </select>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
          <label>How should we get the current time?</label>
          <div class="input-group">
              <span class="input-group-addon">
              <input type="radio" value="client" id="deviceclient" name="currenttimedevice" checked="">
              </span>
              <label class="form-control" for="deviceclient">Use my computer / device</label>
          </div>
          <div class="input-group">
              <span class="input-group-addon">
              <input type="radio" value="server" id="deviceserver" name="currenttimedevice">
              </span>
              <label class="form-control" for="deviceserver">Use the cloud</label>
          </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div id="location-group" class="form-group">
            <label for="location">Location</label>
            <?php
              $locationValue = '';
              if ($city != '' && $country != '') {
                  $locationValue = $city . ', ' . $country;
              }
            ?>
                <input class="form-control" name="location" id="location" value="<?=$locationValue;?>" placeholder="Example: London, UK">
                <span class="form-control-error hide-error" id="location-error">Sorry, we are unable to find this location. Please try another one.</span>
            </div>
    </div>
</div>
<!--
<div class="row">
    <div class="col-md-12">
        <div class="form-group">
            <label>Co-ordinates (Calculated - based on the location)</label>
            <input class="form-control" name="latitude" id="latitude" disabled="disabled" value="" size="5" placeholder="Latitude">
            <input class="form-control" name="longitude" id="longitude" disabled="disabled" value="" size="5" placeholder="Longitude">
        </div>
    </div>
</div>
-->
<div class="form-group">
    <div class="row">
        <div class="col-md-12">
            <label for="latidudeAdjustment">Higher Latitude Adjustment Method (for locations like UK, Sweden, Canada, Alaska, etc.)</label>
             <select class="form-control" name="latiudeAdjustment" id="latiudeAdjustment">
                 <option value="1">Middle of the Night Method</option>
                 <option value="2">One Seventh Rule</option>
                 <option value="3" selected="selected">Angle Based Method </option>
            </select>
        </div>
    </div>
</div>

<div class="form-group">
    <div class="row">
        <div class="col-md-12">
            <label for="juristicSchool">Juristic School (only affects Asr calculation)</label>
             <select class="form-control" name="juristicSchool" id="juristicSchool">
                 <option value="0" selected="selected">Shafi, Hanbali, Maliki, Shia and all others</option>
                 <option value="1">Hanafi</option>
            </select>
        </div>
    </div>
</div>
</form>
      </div>
    </div>
  </div>

</div>
<script src="/js/mediaplayer/build/mediaelement-and-player.min.js"></script>
<script src="/js/play.js?v=10" type="text/javascript"></script>
<script src="/js/jquery.alAdhan.js?v=9" type="text/javascript"></script>
<script>
$(function () {
<?php if(isset($times['timings'])) { ?>
  $.nsAlAdhan._timings = <?=json_encode($times['timings']);?>;
<?php } ?>
  $.nsAlAdhan.init();
})
</script>

<?php include_once('common/footer.phtml'); ?>
