<?php include_once('common/header.phtml'); ?>
<?php include_once('common/navigation.phtml'); ?>
<link rel="stylesheet" href="/css/play.css">
<link rel="stylesheet" href="/js/mediaplayer/build/mediaelementplayer.css" />

<div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-12 col-sm-12 timings" style="">
        <h4 class="pt-heading">Prayer Times <small></small><br /><small></small></h4>
        <img class="minimise-icon" width="21" style="display: none;" src="https://cdn.aladhan.com/images/minimize-icon.png" style="">
        <img class="settings-icon" width="25" style="display: none;" src="https://cdn.aladhan.com/images/settings-icon.png" style="">
        <dl class="inline-flex">
          <dt>Fajr (فجر)</dt>
          <dd class="timeFajr"></dd>
          <dt>Zhuhr (ظهر)</dt>
          <dd class="timeDhuhr"></dd>
          <dt>Asr (عصر)</dt>
          <dd class="timeAsr"></dd>
          <dt>Maghrib (مغرب)</dt>
          <dd class="timeMaghrib"></dd>
          <dt>Isha (عشاء)</dt>
          <dd class="timeIsha"></dd>
        </dl>
        <form role="form">
            <div class="form-group">
                <label for="adhanfile">Select Adhan to play when it's time</label>
                <select id="adhanfile" name="adhanfile" class="form-control">
                    <!--<option value="https://jer3bg-bn1305.files.1drv.com/y4mCw0Bk38pmOQfULyBnvQRUSm1InaFUnsuMtEebnP7jtpnSCxZfAmGcKA7djB87xYaIEAYsROcpl1nXe2ZwPMRgM7Yq1yqWCgUiWrc3I35c06GHBgLL3xH366QjZ7bphEzsZC85mKJz37XM1nyCSDaMf0Oe5Oo1UmL1GDKmcCAxYnXg6wM0Y3CRgHWqysDuT9cNTIlm__XjxQgXoMKKOgDpQ" selected="">Adhan by Ahmad al Nafees</option>
                    <option value="https://kfkfeq-bn1305.files.1drv.com/y4mPz-lVkta8sHWhLyaRn2TYYerb7HhzIJqqcpmBRkitcSAsW0LjqHaFJCElBxy1JUuowh8uCB_kf1tPqpsQeHU4h3UloD7hS1WFfpffX7hvTbvcQC39wqPVaL8CoDRB3imgBzwOUppLhnIgG4BnWeuwBZVugQRZMFa0g52RwFKkPTnVxNLql7n0PF2W4HS2ZqTzUa03Csg8pssWw-Ap50xuA">Adhan by Hafiz Mustafa Özcan from Turkey</option>
                    <option value="https://w83gsw-bn1305.files.1drv.com/y4m6afMxH45s1KnkfhVJwZL5NKYuCC5Y0_lrXoit0dNp_Li8cm7YwNHQHK9-dcQPJWzKTQxiUspP9Lp6cFj6CJEbC9eEPvHm9ErFyfn1gJqTNo3QOBo58OhCSzRZs2swM6ytbB_v5YCizwlZWkPpWkKegQJJkCaY-6VsdyLLDKBeqJNxCkFm9PMkhVf9-d72QawsnEK7XqqwDVHRmTQPWXgWA">Adhan from Karl Jenkins' Mass for Peace"</option>
                    <option value="https://yrqd4q-bn1305.files.1drv.com/y4mosG1crJnfQixz7iV6p3SGJiwAtiq5dfF6KRQFgdx2anU5hP45DaiW9xF4BcDKf8ZAgeLbDLICftQ8swHTYqaI_H1fOA1GKHIdTrKXzQLwziGgCeO5LS3hchSppC0LMdZz0Kz1NOF4VaGlm-fvjnnlbdhg0bIXGVwuAIRxe5myl-bP8jxGj9d0rChSrPCVPrSAeSHVH7I2ajzFJMpe1NEuw">Adhan from Dubai's One TV by Mishary Rashid Alafasy</option>
                    <option value="https://pbyvpq-bn1305.files.1drv.com/y4mYhbHfjJsTiZ9ApXDBwpIY2bqkrm1Ho8t1NUHNiku-dGc194ywveq84g-STb2DvK0n2n3HqqBb0KbeSWwuJnGyUQ-FH7A-yvdGFcVnWW_ZmtwBfZyiuw0HQGpeRIDPACUsu7WKAhmJLmWeuMy8-giJZmROxMaiorkk3ZjFUYoR4qRP91xKnd6fKDEzNJqIK-oC-fbJ1ayYxrU9puy-E8bOg">Another Adhan by Mishary Rashid Alafasy</option>
                    <option value="https://8mqqyw-bn1305.files.1drv.com/y4mGDt9yiGfy9EmjEdj4UcpfU0QiD-vM2FFpKS6mnLv-S7WraaQPi0cTV01DkJib4mB-p8deGIQUxLYmTFjKxzAQ07U7r4xOqQN16E7OJZVcH8MY81EHxy-OU0L71Buywf-awl1v9_sffn024bm_83jgJJY8d3C5nepkDCpI_VaQLXwkoH8CogQLedKGM4tv_VuBBiIsIeG0V5cew9faxpb5A">Another Adhan by Mishary Rashid Alafasy</option>
                    <option value="https://kyu0mw-bn1305.files.1drv.com/y4m35M0BNtXXxbiHs0AvkTkUfCeFXG1flbr3qTzSYmD11-Ghs-CCChFYMmqZI2wPMxVT66n7_y8G1AwRlp90SG-maSYWi8kPy3h5VHinAS_QDlV-Er6X16AyHhsI3zT7UUccPlNiGpcZ2J9MP6SQz7e3X7npS9w29ErJgNM_MettDRNbNI39oOL0WtEbyQOp_CSM93XXOgyvjMdRFYw6G5_4A">Adhan by Qari Abdul Kareem</option>-->
                    <option value="https://cdn.aladhan.com/audio/adhans/a1.mp3" selected="">Adhan by Ahmad al Nafees</option>
                    <option value="https://cdn.aladhan.com/audio/adhans/a2.mp3">Adhan by Hafiz Mustafa Özcan from Turkey</option>
                    <option value="https://cdn.aladhan.com/audio/adhans/a3.mp3">Adhan from Karl Jenkins' Mass for Peace"</option>
                    <option value="https://cdn.aladhan.com/audio/adhans/a4.mp3">Adhan from Dubai's One TV by Mishary Rashid Alafasy</option>
                    <option value="https://cdn.aladhan.com/audio/adhans/a7.mp3">Another Adhan by Mishary Rashid Alafasy</option>
                    <option value="https://cdn.aladhan.com/audio/adhans/a9.mp3">Another Adhan by Mishary Rashid Alafasy</option>
                </select>
            </div>
        </form>
        <hr />
        <div id="holidays" class="hidden"></div>
        <audio id="adhanplayer" src="https://cdn.aladhan.com/audio/adhans/a1.mp3" type="audio/mp3" controls="controls"></audio>
      </div>
      <div class="col-lg-9 col-md-12 col-sm-12 timings-settings" style="background-color: black; opacity: 0.8; margin: 10 0 0 0;">
        <div class="loader">
            <img src="/images/loader.svg" />
            <div>Loading</div>
        </div>
        <img class="settings-close-icon" width="25" src="https://cdn.aladhan.com/images/close-icon.png">
<?php include_once('common/bismillah.phtml'); ?>
        <div class="page-header">
            <h4>Adhan Player <small>Just select a method and enter a location</small></h2>
        </div>

        <form role="form">
          <div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label for="method">Method (<a href="/calculation-methods" target="_blank">Learn more about calculation methods</a>)</label>
            <select id="method" name="method" class="form-control">
                <option value="0">Shia Ithna-Ashari</option>
                <option value="1">University of Islamic Sciences, Karachi</option>
                <option value="2" selected>Islamic Society of North America (ISNA)</option>
                <option value="3">Muslim World League (MWL)</option>
                <option value="4">Umm al-Qura, Makkah</option>
                <option value="5">Egyptian General Authority of Survey</option>
                <option value="7">Institute of Geophysics, University of Tehran</option>
                <option value="8">Gulf Region</option>
                <option value="9">Kuwait</option>
                <option value="10">Qatar</option>
                <option value="11">Majlis Ugama Islam Singapura, Singapore</option>
                <option value="12">Union Organization Islamic de France</option>
            </select>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
          <label>How should we get the current time?</label>
          <div class="input-group">
              <span class="input-group-addon">
              <input type="radio" value="client" id="deviceclient" name="currenttimedevice" checked="">
              </span>
              <label class="form-control" for="deviceclient">Use my computer / device</label>
          </div>
          <div class="input-group">
              <span class="input-group-addon">
              <input type="radio" value="server" id="deviceserver" name="currenttimedevice">
              </span>
              <label class="form-control" for="deviceserver">Use the cloud</label>
          </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="form-group">
            <label for="location">Location</label>
            <?php
              $locationValue = '';
              if ($city != '' && $country != '') {
                  $locationValue = $city . ', ' . $country;
              }
            ?>
                <input class="form-control" name="location" id="location" value="<?=$locationValue;?>" placeholder="Example: London, UK">
            </div>
    </div>
</div>
<!--
<div class="row">
    <div class="col-md-12">
        <div class="form-group">
            <label>Co-ordinates (Calculated - based on the location)</label>
            <input class="form-control" name="latitude" id="latitude" disabled="disabled" value="" size="5" placeholder="Latitude">
            <input class="form-control" name="longitude" id="longitude" disabled="disabled" value="" size="5" placeholder="Longitude">
        </div>
    </div>
</div>
-->
<div class="form-group">
    <div class="row">
        <div class="col-md-12">
            <label for="latidudeAdjustment">Higher Latitude Adjustment Method (for locations like UK, Sweden, Canada, Alaska, etc.)</label>
             <select class="form-control" name="latiudeAdjustment" id="latiudeAdjustment">
                 <option value="1">Middle of the Night Method</option>
                 <option value="2">One Seventh Rule</option>
                 <option value="3" selected="selected">Angle Based Method </option>
            </select>
        </div>
    </div>
</div>

<div class="form-group">
    <div class="row">
        <div class="col-md-12">
            <label for="juristicSchool">Juristic School (only affects Asr calculation)</label>
             <select class="form-control" name="juristicSchool" id="juristicSchool">
                 <option value="0" selected="selected">Shafi, Hanbali, Maliki, Shia and all others</option>
                 <option value="1">Hanafi</option>
            </select>
        </div>
    </div>
</div>
</form>
      </div>
    </div>
  </div>

</div>
<script src="/js/mediaplayer/build/mediaelement-and-player.min.js"></script>
<script src="/js/play.js" type="text/javascript"></script>
<script src="/js/jquery.alAdhan.js" type="text/javascript"></script>
<script>
$(function () {
  $.nsAlAdhan.init();
})
</script>

<?php include_once('common/footer.phtml'); ?>
