<?php include_once('common/header.phtml'); ?>
<?php include_once('common/navigation.phtml'); ?>

<div class="panel" style="background-color: whitesmoke; margin-top: 50px; opacity: 100%;">
    <?php include_once('common/bismillah.phtml'); ?>

    <div class="page-header">
        <h2 style="color: black">Prayer Times API</h2>
    </div>
    <redoc spec-url="https://raw.githubusercontent.com/islamic-network/openapi/master/aladhan-api/combined.yaml"></redoc>
    <script src="https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js"> </script>


</div>
<?php include_once('common/footer.phtml'); ?>
