<?php include_once('common/header.phtml'); ?>
<?php include_once('common/navigation.phtml'); ?>

<div class="container panel">
    <?php include_once('common/bismillah.phtml'); ?>

	<div class="page-header">
        <h2>Ramadan Calendar - <?=$gy;?> / <?=$y;?><h2>
    </div>
	<p>
		Please note that the below dates are computed mathematically and may be inaccurate by one day.
	</p>
    <form role="form" action="/ramadan--calendar/<?=$gy;?>" method="GET" class="hidden" id="calconfig">
		<div class="row">
			<div class="col-md-12">
				<div class="form-group">
					<label for="year">Year</label>
					<input type="text" class="form-control" id="year" name="y" value="<?php echo $gy; ?>"/>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12 col-centered">
				<button type="submit" id="updateCal" class="btn btn-primary" >
					Update Calendar
				</button>
			</div>
		</div>
	</form>
	<div class="row">
		<div class="col-md-12" style="text-align: right">
			<span class="btn btn-primary" title="Configuration Options" id="configBtn">+</span>
		</div>
	</div>

    <div class="row">
		<div class="col-md-1 col-lg-1 col-xs-1">
			<a href="<?php echo $prevMonth; ?>" class="btn btn-large glyphicon glyphicon-chevron-left"></a>
		</div>
<?php
$days = [ 0 =>'Sunday', 1 => 'Monday', 2 => 'Tuesday', 3 => 'Wednesday', 4 => 'Thursday', 5 => 'Friday', 6 => 'Saturday'];
?>
        <div class="col-md-10 col-lg-10 col-xs-1 col-sm-1">
        <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
        <?php foreach ($days as $wday) {?>
            <td>
                <?=$wday;?>
            </td>
        <?php } ?>
            </tr>
        </thead>
        <tbody>
        <?php $x = 1; ?>
		<?php for($row=0; $row<=$rows; $row++) { ?>
            <tr>
            <?php for($col=0; $col<$cols; $col++) { ?>
                <td class="<?php echo (date('d') == $calendar[$y][$m]['days'][$x]['gregorian']['day'] && date('m') == $calendar[$y][$m]['days'][$x]['gregorian']['month']['number'] && date('Y') == $calendar[$y][$m]['days'][$x]['gregorian']['year'] ) ? 'danger' : '' ?>" style="padding-top: 10px; padding-bottom: 15px; padding-left: 3px;">
                <?php if ($days[$col] == $calendar[$y][$m]['days'][$x]['gregorian']['weekday']['en']) { ?>
					<?php if (isset($calendar[$y][$m]['days'][$x])) { ?>
                    <span><?php echo $calendar[$y][$m]['days'][$x]['hijri']['day'] ; ?>
                    <?php echo $calendar[$y][$m]['days'][$x]['hijri']['month']['en'] ; ?></span>
                    <!--<br /><span><?php echo $calendar[$y][$m]['days'][$x]['hijri']['weekday']['ar']; ?></span>-->
					<br />
                    <span><?php echo $calendar[$y][$m]['days'][$x]['gregorian']['day'] ; ?>
                    <?php echo $calendar[$y][$m]['days'][$x]['gregorian']['month']['en'] ; ?><!--<br /><?php echo $calendar[$y][$m]['days'][$x]['gregorian']['weekday']['en'] ; ?>--></span>
						<?php if (isset($calendar[$y][$m]['days'][$x]['holidays']) && !empty($calendar[$y][$m]['days'][$x]['holidays'])) { ?>
							<br />
							<?php foreach ($calendar[$y][$m]['days'][$x]['holidays'] as $h) { ?>
							<span class="bg-danger"><?php echo $h; ?></span>
							<br />
							<?php } ?>
						<?php } ?>
					<?php $x++; }} ?>
                </td>
			<?php    } ?>
            </tr>
		<?php }  ?>
            </tbody>
        </table>
        </div>
        <div class="col-md-1">
			<a href="<?php echo $nextMonth; ?>" class="btn btn-large glyphicon glyphicon-chevron-right"></a>
		</div>
    </div>
</div><!-- /.container -->
<script>
$(function() {
	$('#configBtn').on('click', function() {
		var val = $(this).text();
		if(val == '+') {
			$('#calconfig').removeClass('hidden');
			$(this).text('-');
		}
		if(val == '-') {
			$('#calconfig').addClass('hidden');
			$(this).text('+');
		}
	});
});
</script>
<script>
$(function() {
    $('#year').on('change', function() {
        var y = $(this).val();
        $('#calconfig').attr('action', '/ramadan-calendar/' + y);
    });
    $('#updateCal').on('click', function(e) {
        e.preventDefault();
        var url = $('#calconfig').attr('action');
        window.location.href = url;
    });
});
</script>

<?php include_once('common/footer.phtml'); ?>
