<?php include_once('common/header.phtml'); ?>
<?php include_once('common/navigation.phtml'); ?>

<div class="container panel">
    <?php include_once('common/bismillah.phtml'); ?>
    <div class="page-header">
        <h2>Credits, Terms and Conditions</h2>
    </div>
    <p>
        AlAdhan.com is part of the <a href="https://islamic.network" target="_blank">Islamic Network</a>.
    </p>    

    <h2>Credits</h2>
    <p>
        First and foremost, praise belongs to God Almighty, who has given us the ability to do this. And then thanks to my wife, for her continued patience whilst we work to keep this service up and running, by God's grace.
    </p>
    <p>
        This site uses code / resources from the following frameworks / sources / companies:
    </p>
    <ul>
        <li><a href="http://praytimes.org">Pray Times</a> - The code for the primary API is based almost in its entirety on the libraries on this website. Thank you to <a href="http://zarrabi.info/" target="_blank">Hamid Zarrabi-Zadeh</a> of Sharif University of Technology in Iran for this.</li>
        <li><a href="http://www.getbootstrap.com">Bootsrap 3</a> - The framework used to build the GUI on this website.</li>
        <li><a href="http://jquery.com">jQuery</a> - The JavasScript framework used by Bootstrap 3 and other elements on this website.</li>
        <li><a href="https://github.com/Seldaek/monolog">Monolog</a></li>
        <li><a href="http://7x.ax">7x</a> - For allowing usage of their APIs for geocoding and timezone calculations.</li>
        <li><a href="http://mamluk.net">Mamluk</a> - For providing hosting.</li>
        <li>Layth A. Ibraheem - The Hijri / Gregorian Date Converter is built on modified code originally written by him.</li>
        <li>And of course - Linux, Apache, PHP, CircleCI, Docker, Kubernetes, Pelias, OpenStreetMap and Evan Siroky.</li>
    </ul>

    <h2>Terms and Conditions</h2>
    <p>
        This website, API and all the services herein are made available in the hope that they will be useful,
        but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
        The prayer times computed may not be accurate by some standards and are computed based on the calculations, methods and formulas discussed 
        on praytimes.org.
    </p>

    <p>
        All audio files used on this website and third party libraries own and retain their respective copyrights.
    </p>
</div>

<?php include_once('common/footer.phtml'); ?>
