<?php include_once('common/header.phtml'); ?>
<?php include_once('common/navigation.phtml'); ?>

<div class="container panel">
    <?php include_once('common/bismillah.phtml'); ?>
    <div class="page-header">
        <h2>Credits, Terms and Conditions</h2>
    </div>
    

    <h2>Credits</h2>
    <p>
        This site uses code / resources from the following frameworks / sources / companies:
    </p>
    <ul>
        <li><a href="http://praytimes.org">Pray Times</a> - The code for the primary API is based almost in its entirety on the libraries on this website. Thank you to <a href="http://zarrabi.info/" target="_blank">Hamid Zarrabi-Zadeh</a> of Sharif University of Technology in Iran for this.</li>
        <li><a href="http://mediaelementjs.com/">Media Element.js</a> - This is the media player used to stream Adhan.</li>
        <li><a href="http://www.getbootstrap.com">Bootsrap 3</a> - The framework used to build the GUI on this website.</li>
        <li><a href="http://jquery.com">jQuery</a> - The JavasScript framework used by Bootstrap 3 and other elements on this website.</li>
        <li><a href="https://github.com/Seldaek/monolog">Monolog</a></li>
        <li><a href="http://geonames.org">GeoNames</a> - For a list of cities across the world (and co-ordinates available with the locations).</li>
        <li><a href="http://vesica.ws">Vesica</a> - For providing hosting.</li>
        <li><a href="http://google.com">Google</a> - For the Google Maps geolocation and timezone APIs.</li>
        <li>Layth A. Ibraheem - The Hijri / Gregorian Date Converter is built on modified code originally written by him.</li>
        <li>And of course - Linux, Apache and PHP.</li>
    </ul>

    <h2>Terms and Conditions</h2>
    <p>
        This website, API and all the services herein are made available in the hope that they will be useful,
        but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
        The prayer times computed may not be accurate by some standards and are computed based on the calculations, methods and formulas discussed 
        on praytimes.org.
    </p>

    <p>
        All audio files used on this website and third party libraries own and retain their respective copyrights.
    </p>
</div>

<?php include_once('common/footer.phtml'); ?>
